micronaut:
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
endpoints:
  metrics:
    enabled: true
    sensitive: false
  prometheus:
    enabled: true
    sensitive: false